name: Sync Repositories

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  sync:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip
          # If you have dependencies, list them here (e.g., pip install -r requirements.txt)

      - name: Run sync script
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}  # Use secrets for sensitive information
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use secrets for sensitive information
        run: python path/to/your_script.py  # Update the path to your script
