name: Sync Repos

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger on

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install any additional dependencies your script may require

      - name: Run sync script
        run: |
          python sync_repos.py  # Adjust the filename if your script has a different name
        
      - name: Check for failed syncs
        run: |
          if [ -f failed_repos.txt ]; then
            echo "Some repositories failed to sync. See 'failed_repos.txt' for details."
            exit 1
          fi
